// Curated FA6 icon list. Default type is 'solid'; brand icons use type 'brands'.
// FA6 solid requires font-weight: 900; brands require font-weight: 400.

export const icons = [
  // Arrows & Navigation
  { value: 'arrow-down', label: 'Arrow: Down' },
  { value: 'arrow-left', label: 'Arrow: Left' },
  { value: 'arrow-right', label: 'Arrow: Right' },
  { value: 'arrow-up', label: 'Arrow: Up' },
  { value: 'arrows-up-down-left-right', label: 'Arrows' },
  { value: 'arrow-up-right-from-square', label: 'External Link' },
  { value: 'chevron-down', label: 'Chevron: Down' },
  { value: 'chevron-left', label: 'Chevron: Left' },
  { value: 'chevron-right', label: 'Chevron: Right' },
  { value: 'chevron-up', label: 'Chevron: Up' },
  { value: 'caret-down', label: 'Caret: Down' },
  { value: 'caret-left', label: 'Caret: Left' },
  { value: 'caret-right', label: 'Caret: Right' },
  { value: 'caret-up', label: 'Caret: Up' },
  { value: 'compass', label: 'Compass' },
  { value: 'location-dot', label: 'Location' },
  { value: 'location-arrow', label: 'Location Arrow' },

  // Actions
  { value: 'ban', label: 'Ban' },
  { value: 'check', label: 'Check' },
  { value: 'circle-check', label: 'Check (Circle)' },
  { value: 'square-check', label: 'Check (Square)' },
  { value: 'circle-xmark', label: 'Times (Circle)' },
  { value: 'copy', label: 'Copy' },
  { value: 'download', label: 'Download' },
  { value: 'pen-to-square', label: 'Edit' },
  { value: 'eraser', label: 'Eraser' },
  { value: 'expand', label: 'Expand' },
  { value: 'filter', label: 'Filter' },
  { value: 'lock', label: 'Lock' },
  { value: 'unlock', label: 'Unlock' },
  { value: 'magnifying-glass', label: 'Search' },
  { value: 'magnifying-glass-minus', label: 'Search: Minus' },
  { value: 'magnifying-glass-plus', label: 'Search: Plus' },
  { value: 'paper-plane', label: 'Paper Plane' },
  { value: 'paperclip', label: 'Paper Clip' },
  { value: 'pencil', label: 'Pencil' },
  { value: 'square-pen', label: 'Pencil (Square)' },
  { value: 'plus', label: 'Plus' },
  { value: 'circle-plus', label: 'Plus (Circle)' },
  { value: 'square-plus', label: 'Plus (Square)' },
  { value: 'print', label: 'Print' },
  { value: 'rotate', label: 'Refresh' },
  { value: 'rotate-left', label: 'Rotate Left' },
  { value: 'rotate-right', label: 'Rotate Right' },
  { value: 'floppy-disk', label: 'Save' },
  { value: 'scissors', label: 'Scissors' },
  { value: 'share-nodes', label: 'Share' },
  { value: 'share-from-square', label: 'Share (Square)' },
  { value: 'right-to-bracket', label: 'Sign In' },
  { value: 'right-from-bracket', label: 'Sign Out' },
  { value: 'sort', label: 'Sort' },
  { value: 'sort-up', label: 'Sort: Asc' },
  { value: 'sort-down', label: 'Sort: Desc' },
  { value: 'thumbs-down', label: 'Thumbs Down' },
  { value: 'thumbs-up', label: 'Thumbs Up' },
  { value: 'trash', label: 'Trash' },
  { value: 'upload', label: 'Upload' },
  { value: 'xmark', label: 'Times' },

  // Objects & UI
  { value: 'ambulance', label: 'Ambulance' },
  { value: 'anchor', label: 'Anchor' },
  { value: 'box-archive', label: 'Archive' },
  { value: 'asterisk', label: 'Asterisk' },
  { value: 'backward', label: 'Backward' },
  { value: 'barcode', label: 'Barcode' },
  { value: 'bars', label: 'Bars' },
  { value: 'beer-mug-empty', label: 'Beer' },
  { value: 'bell', label: 'Bell' },
  { value: 'bold', label: 'Bold' },
  { value: 'bolt', label: 'Bolt' },
  { value: 'bomb', label: 'Bomb' },
  { value: 'book', label: 'Book' },
  { value: 'bookmark', label: 'Bookmark' },
  { value: 'briefcase', label: 'Briefcase' },
  { value: 'bug', label: 'Bug' },
  { value: 'building', label: 'Building' },
  { value: 'building-columns', label: 'Institution' },
  { value: 'bullhorn', label: 'Bullhorn' },
  { value: 'bullseye', label: 'Bullseye' },
  { value: 'calendar', label: 'Calendar' },
  { value: 'camera', label: 'Camera' },
  { value: 'car', label: 'Car' },
  { value: 'certificate', label: 'Certificate' },
  { value: 'chart-bar', label: 'Bar Chart' },
  { value: 'child', label: 'Child' },
  { value: 'circle', label: 'Circle' },
  { value: 'clipboard', label: 'Clipboard' },
  { value: 'clock', label: 'Clock' },
  { value: 'cloud', label: 'Cloud' },
  { value: 'cloud-arrow-down', label: 'Cloud: Download' },
  { value: 'cloud-arrow-up', label: 'Cloud: Upload' },
  { value: 'code', label: 'Code' },
  { value: 'code-fork', label: 'Code (Fork)' },
  { value: 'coffee', label: 'Coffee' },
  { value: 'gear', label: 'Cog' },
  { value: 'gears', label: 'Cogs' },
  { value: 'columns', label: 'Columns' },
  { value: 'comment', label: 'Comment' },
  { value: 'comments', label: 'Comments' },
  { value: 'credit-card', label: 'Credit Card' },
  { value: 'crop', label: 'Crop' },
  { value: 'crosshairs', label: 'Crosshairs' },
  { value: 'cube', label: 'Cube' },
  { value: 'cubes', label: 'Cubes' },
  { value: 'database', label: 'Database' },
  { value: 'desktop', label: 'Desktop' },
  { value: 'dollar-sign', label: 'Dollar' },
  { value: 'droplet', label: 'Droplet' },
  { value: 'eject', label: 'Eject' },
  { value: 'ellipsis', label: 'Ellipsis (H)' },
  { value: 'ellipsis-vertical', label: 'Ellipsis (V)' },
  { value: 'envelope', label: 'Envelope' },
  { value: 'euro-sign', label: 'Euro' },
  { value: 'exchange-alt', label: 'Exchange' },
  { value: 'circle-exclamation', label: 'Exclamation (Circle)' },
  { value: 'triangle-exclamation', label: 'Exclamation (Triangle)' },
  { value: 'eye', label: 'Eye' },
  { value: 'eye-slash', label: 'Eye (Slash)' },
  { value: 'fast-backward', label: 'Fast Rewind' },
  { value: 'fast-forward', label: 'Fast Forward' },
  { value: 'fax', label: 'Fax' },
  { value: 'fighter-jet', label: 'Fighter Jet' },
  { value: 'file', label: 'File' },
  { value: 'file-code', label: 'File: Code' },
  { value: 'film', label: 'Film' },
  { value: 'fire', label: 'Fire' },
  { value: 'fire-extinguisher', label: 'Fire Extinguisher' },
  { value: 'flag', label: 'Flag' },
  { value: 'flag-checkered', label: 'Flag: Checkered' },
  { value: 'flask', label: 'Flask' },
  { value: 'folder', label: 'Folder' },
  { value: 'folder-open', label: 'Folder: Open' },
  { value: 'font', label: 'Font' },
  { value: 'forward', label: 'Forward' },
  { value: 'face-frown', label: 'Frown' },
  { value: 'gamepad', label: 'Gamepad' },
  { value: 'gavel', label: 'Gavel' },
  { value: 'sterling-sign', label: 'GBP' },
  { value: 'gift', label: 'Gift' },
  { value: 'globe', label: 'Globe' },
  { value: 'graduation-cap', label: 'Graduation Cap' },
  { value: 'h-square', label: 'H (Square)' },
  { value: 'hand-point-down', label: 'Hand: Down' },
  { value: 'hand-point-left', label: 'Hand: Left' },
  { value: 'hand-point-right', label: 'Hand: Right' },
  { value: 'hand-point-up', label: 'Hand: Up' },
  { value: 'hard-drive', label: 'HDD' },
  { value: 'heading', label: 'Heading' },
  { value: 'headphones', label: 'Headphones' },
  { value: 'heart', label: 'Heart' },
  { value: 'history', label: 'History' },
  { value: 'house', label: 'Home' },
  { value: 'hospital', label: 'Hospital' },
  { value: 'image', label: 'Image' },
  { value: 'inbox', label: 'Inbox' },
  { value: 'indent', label: 'Indent' },
  { value: 'circle-info', label: 'Info (Circle)' },
  { value: 'italic', label: 'Italic' },
  { value: 'key', label: 'Key' },
  { value: 'keyboard', label: 'Keyboard' },
  { value: 'language', label: 'Language' },
  { value: 'laptop', label: 'Laptop' },
  { value: 'leaf', label: 'Leaf' },
  { value: 'life-ring', label: 'Life Ring' },
  { value: 'lightbulb', label: 'Lightbulb' },
  { value: 'link', label: 'Link' },
  { value: 'link-slash', label: 'Link (Broken)' },
  { value: 'list', label: 'List' },
  { value: 'list-ol', label: 'List (OL)' },
  { value: 'list-ul', label: 'List (UL)' },
  { value: 'lock', label: 'Lock' },
  { value: 'wand-magic-sparkles', label: 'Magic' },
  { value: 'magnet', label: 'Magnet' },
  { value: 'male', label: 'Male' },
  { value: 'kit-medical', label: 'Medkit' },
  { value: 'face-meh', label: 'Meh' },
  { value: 'microphone', label: 'Microphone' },
  { value: 'microphone-slash', label: 'Microphone (Slash)' },
  { value: 'minus', label: 'Minus' },
  { value: 'circle-minus', label: 'Minus (Circle)' },
  { value: 'square-minus', label: 'Minus (Square)' },
  { value: 'mobile', label: 'Mobile' },
  { value: 'money-bill', label: 'Money' },
  { value: 'moon', label: 'Moon' },
  { value: 'music', label: 'Music' },
  { value: 'outdent', label: 'Outdent' },
  { value: 'paragraph', label: 'Paragraph' },
  { value: 'pause', label: 'Pause' },
  { value: 'paw', label: 'Paw' },
  { value: 'phone', label: 'Phone' },
  { value: 'phone-square', label: 'Phone (Square)' },
  { value: 'plane', label: 'Plane' },
  { value: 'play', label: 'Play' },
  { value: 'circle-play', label: 'Play (Circle)' },
  { value: 'plug', label: 'Plug' },
  { value: 'power-off', label: 'Power Off' },
  { value: 'puzzle-piece', label: 'Puzzle Piece' },
  { value: 'qrcode', label: 'QR Code' },
  { value: 'question', label: 'Question' },
  { value: 'circle-question', label: 'Question (Circle)' },
  { value: 'quote-left', label: 'Quote: Left' },
  { value: 'quote-right', label: 'Quote: Right' },
  { value: 'shuffle', label: 'Random' },
  { value: 'recycle', label: 'Recycle' },
  { value: 'reply', label: 'Reply' },
  { value: 'reply-all', label: 'Reply All' },
  { value: 'retweet', label: 'Retweet' },
  { value: 'road', label: 'Road' },
  { value: 'rocket', label: 'Rocket' },
  { value: 'rss', label: 'RSS' },
  { value: 'ruble-sign', label: 'Ruble' },
  { value: 'indian-rupee-sign', label: 'Rupee' },
  { value: 'shield', label: 'Shield' },
  { value: 'shield-halved', label: 'Shield (Alt)' },
  { value: 'cart-shopping', label: 'Shopping Cart' },
  { value: 'signal', label: 'Signal' },
  { value: 'sitemap', label: 'Sitemap' },
  { value: 'sliders', label: 'Sliders' },
  { value: 'face-smile', label: 'Smile' },
  { value: 'snowflake', label: 'Snowflake' },
  { value: 'space-shuttle', label: 'Space Shuttle' },
  { value: 'spinner', label: 'Spinner' },
  { value: 'utensil-spoon', label: 'Spoon' },
  { value: 'square', label: 'Square' },
  { value: 'star', label: 'Star' },
  { value: 'star-half', label: 'Star (Half)' },
  { value: 'star-half-stroke', label: 'Star (Half Stroke)' },
  { value: 'step-backward', label: 'Step Backward' },
  { value: 'step-forward', label: 'Step Forward' },
  { value: 'stethoscope', label: 'Stethoscope' },
  { value: 'stop', label: 'Stop' },
  { value: 'strikethrough', label: 'Strikethrough' },
  { value: 'subscript', label: 'Subscript' },
  { value: 'suitcase', label: 'Suitcase' },
  { value: 'sun', label: 'Sun' },
  { value: 'superscript', label: 'Superscript' },
  { value: 'table', label: 'Table' },
  { value: 'tablet', label: 'Tablet' },
  { value: 'gauge', label: 'Tachometer' },
  { value: 'tag', label: 'Tag' },
  { value: 'tags', label: 'Tags' },
  { value: 'list-check', label: 'Tasks' },
  { value: 'taxi', label: 'Taxi' },
  { value: 'terminal', label: 'Terminal' },
  { value: 'text-height', label: 'Text Height' },
  { value: 'text-width', label: 'Text Width' },
  { value: 'table-cells-large', label: 'Th (Large)' },
  { value: 'table-list', label: 'Th (List)' },
  { value: 'thumbtack', label: 'Thumb Tack' },
  { value: 'ticket', label: 'Ticket' },
  { value: 'tree', label: 'Tree' },
  { value: 'trophy', label: 'Trophy' },
  { value: 'truck', label: 'Truck' },
  { value: 'turkish-lira-sign', label: 'Turkish Lira' },
  { value: 'umbrella', label: 'Umbrella' },
  { value: 'underline', label: 'Underline' },
  { value: 'university', label: 'University' },
  { value: 'user', label: 'User' },
  { value: 'user-doctor', label: 'User (Doctor)' },
  { value: 'users', label: 'Users' },
  { value: 'video', label: 'Video' },
  { value: 'volume-high', label: 'Volume Up' },
  { value: 'volume-low', label: 'Volume Down' },
  { value: 'volume-xmark', label: 'Volume Off' },
  { value: 'wheelchair', label: 'Wheelchair' },
  { value: 'won-sign', label: 'Won' },
  { value: 'wrench', label: 'Wrench' },
  { value: 'yen-sign', label: 'Yen' },

  // Brand icons
  { value: 'android', label: 'Android', type: 'brands' },
  { value: 'apple', label: 'Apple', type: 'brands' },
  { value: 'behance', label: 'Behance', type: 'brands' },
  { value: 'bitbucket', label: 'BitBucket', type: 'brands' },
  { value: 'bitcoin', label: 'Bitcoin', type: 'brands' },
  { value: 'chrome', label: 'Chrome', type: 'brands' },
  { value: 'codepen', label: 'Codepen', type: 'brands' },
  { value: 'css3', label: 'CSS3', type: 'brands' },
  { value: 'deviantart', label: 'Deviantart', type: 'brands' },
  { value: 'discord', label: 'Discord', type: 'brands' },
  { value: 'docker', label: 'Docker', type: 'brands' },
  { value: 'dribbble', label: 'Dribbble', type: 'brands' },
  { value: 'dropbox', label: 'Dropbox', type: 'brands' },
  { value: 'drupal', label: 'Drupal', type: 'brands' },
  { value: 'facebook', label: 'Facebook', type: 'brands' },
  { value: 'flickr', label: 'Flickr', type: 'brands' },
  { value: 'git', label: 'Git', type: 'brands' },
  { value: 'github', label: 'GitHub', type: 'brands' },
  { value: 'github-alt', label: 'GitHub (Alt)', type: 'brands' },
  { value: 'google', label: 'Google', type: 'brands' },
  { value: 'html5', label: 'HTML5', type: 'brands' },
  { value: 'instagram', label: 'Instagram', type: 'brands' },
  { value: 'joomla', label: 'Joomla', type: 'brands' },
  { value: 'jsfiddle', label: 'JSFiddle', type: 'brands' },
  { value: 'linkedin', label: 'LinkedIn', type: 'brands' },
  { value: 'linux', label: 'Linux', type: 'brands' },
  { value: 'npm', label: 'npm', type: 'brands' },
  { value: 'pagelines', label: 'Pagelines', type: 'brands' },
  { value: 'pinterest', label: 'Pinterest', type: 'brands' },
  { value: 'reddit', label: 'Reddit', type: 'brands' },
  { value: 'skype', label: 'Skype', type: 'brands' },
  { value: 'slack', label: 'Slack', type: 'brands' },
  { value: 'soundcloud', label: 'Soundcloud', type: 'brands' },
  { value: 'spotify', label: 'Spotify', type: 'brands' },
  { value: 'stack-overflow', label: 'Stack Overflow', type: 'brands' },
  { value: 'steam', label: 'Steam', type: 'brands' },
  { value: 'trello', label: 'Trello', type: 'brands' },
  { value: 'tumblr', label: 'Tumblr', type: 'brands' },
  { value: 'x-twitter', label: 'X (Twitter)', type: 'brands' },
  { value: 'vimeo', label: 'Vimeo', type: 'brands' },
  { value: 'vk', label: 'VK', type: 'brands' },
  { value: 'weibo', label: 'Weibo', type: 'brands' },
  { value: 'windows', label: 'Windows', type: 'brands' },
  { value: 'wordpress', label: 'WordPress', type: 'brands' },
  { value: 'xing', label: 'Xing', type: 'brands' },
  { value: 'yahoo', label: 'Yahoo', type: 'brands' },
  { value: 'youtube', label: 'YouTube', type: 'brands' },
]
