name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: dynamicskillset/.github/.github/workflows/deploy-static-site.yml@main
    with:
      deploy-path: /opt/ghost/sites/dynamicskillset.com/badge-studio
    secrets: inherit
